name: test-py

on: [push]

jobs:
  build:
    name: autopy-lot-py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: autopy-lot 
        uses: VladimirFokow/autopy-lot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_type: py
